settings:
    LOGGING_DIR: '/project/catinous/active_catinous/MELBA/log/tensorboard_logs/'
    TRAINED_MODELS_DIR: '/project/catinous/active_catinous/MELBA/output/trained_models/'
    TRAINED_MEMORY_DIR: '/project/catinous/active_catinous/MELBA/output/trained_memory/'
    RESULT_DIR: '/project/catinous/active_catinous/MELBA/output/results/'

trainparams:
    task: 'brainage'
    method: 'uncertainty'
    startbudget: 378
    uncertainty_threshold: 6.0
    uncertainty_iterations: 20
    continuous: True
    use_memory: True
    random_cache: True
    datasetfile: '/project/catinous/brainds_split_val_test_melba.csv'
    transition_phase_after: 0.8
    batch_size: 4
    training_batch_size: 8
    order: ['1.5T Philips', '1.5T', '3.0T Philips', '3.0T']
    scanner: null
    base_model: 'brainage_batch_brainds_split_val_test_melba_base_1_81207b7536.pt'
    val_check_interval: 10
    memorymaximum: 64
    droprate: 0.25
    learning_rate: 0.0001
    gradient_clip_val: 0.5
    allowedlabelratio: 0
    dim: 3
    run_postfix: 1
    seed: 1