settings:
    LOGGING_DIR: '/project/catinous/active_catinous/MELBA/log/tensorboard_logs/'
    TRAINED_MODELS_DIR: '/project/catinous/active_catinous/MELBA/output/trained_models/'
    TRAINED_MEMORY_DIR: '/project/catinous/active_catinous/MELBA/output/trained_memory/'
    RESULT_DIR: '/project/catinous/active_catinous/MELBA/output/results/'

trainparams:
    task: 'brainage'
    method: 'casa'
    startbudget: 95
    outlier_distance: 0.80 #0.60
    continuous: True
    use_memory: True
    random_cache: True
    transformgrams: True
    datasetfile: '/project/catinous/brainds_split_val_test_melba.csv'
    transition_phase_after: 0.8
    batch_size: 2
    training_batch_size: 4
    order: ['1.5T Philips', '1.5T', '3.0T Philips', '3.0T']
    scanner: null
    base_model: 'brainage_batch_brainds_split_val_test_melba_base_1_9fd356bd91.pt'
    val_check_interval: 10
    memorymaximum: 128
    completion_limit: 5.0
    droprate: 0.0
    fulldrop: True
    learning_rate: 0.00001
    gradient_clip_val: 0.5
    allowedlabelratio: 0
    len_perf_queue: 8
    dim: 3
    run_postfix: 1
    seed: 1