settings:
    LOGGING_DIR: '/project/catinous/active_catinous/MELBA/log/tensorboard_logs/'
    TRAINED_MODELS_DIR: '/project/catinous/active_catinous/MELBA/output/trained_models/'
    TRAINED_MEMORY_DIR: '/project/catinous/active_catinous/MELBA/output/trained_memory/'
    RESULT_DIR: '/project/catinous/active_catinous/MELBA/output/results/'

trainparams:
    method: 'naive'
    task: 'lidc'
    naive_insert_rate: 20
    startbudget: 44
    continuous: True
    use_memory: True
    random_cache: True
    datasetfile: '/project/catinous/lungnodulesfinallndbBig.csv'
    transition_phase_after: 0.8
    batch_size: 4
    training_batch_size: 8
    order: ['ges', 'geb', 'sie', 'lndb']
    scanner: null
    base_model: 'lidc_batch_lungnodulesfinallndbBig_base_1_f537b60b93.pt'
    run_postfix: 1
    val_check_interval: 10
    memorymaximum: 128
    droprate: 0.0
    learning_rate: 0.00001
    gradient_clip_val: 0.5
    allowedlabelratio: 0
    dim: 2
    seed: 1