binary: '/home/cir/mperkonigg/env/catinous/bin/python',
cwd: '/home/cir/mperkonigg/catinous/active_catinous/',
gpu: 1,
partition: 'centos7',
memory: 100000,
constraint: 'bigGPUmem',
jobname: 'adm',
outputpath: '/home/cir/mperkonigg/slurmoutput/',
mailuser: 'matthias.perkonigg@meduniwien.ac.at',
minutes: '300'